Repository chandrahmani/hello-travel, pull requests merged in 2023-03, with the labels that each got.

#12 Router v6 implementations
  package-lock.json
  package.json
  src/App.jsx
  src/components/core/navbar/Navbar.jsx
  src/main.jsx
  src/pages/AboutPage.jsx
  src/pages/ContactPage.jsx
  src/pages/ErrorPage.jsx
  src/pages/HomePage.jsx
  src/pages/Root.jsx
  vite.config.js
Labels: enhancement, feature

#14 implemented ESLint and prettier
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  vite.config.js
Labels: enhancement, feature

#17 Code refactor
  .eslintrc.json
  package-lock.json
  package.json
  src/App.jsx
  src/components/core/footer/Footer.jsx
  src/components/core/queryForm/QueryForm.css
  src/components/core/queryForm/QueryForm.jsx
  src/components/core/styled/index.js
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/components/views/ErrorPage.jsx
  src/components/views/about/About.jsx
  src/components/views/contact/Contact.jsx
  src/components/views/home/adventure/Adventure.jsx
  src/components/views/home/banner/Banner.css
  src/components/views/home/banner/Banner.jsx
  src/components/views/home/service/Service.jsx
  src/components/views/home/travelDetails/TravelDetails.jsx
  src/main.jsx
  src/pages/ContactPage.jsx
  src/pages/HomePage.jsx
  src/pages/Root.jsx
Labels: enhancement

#18 updated hello travel then added
  src/App.jsx
  src/components/core/footer/Footer.css
  src/components/core/footer/Footer.jsx
  src/components/core/query-form/QueryForm.css
  src/components/core/query-form/QueryForm.jsx
  src/components/core/styled/index.js
  src/components/views/about/About.css
  src/components/views/about/About.jsx
  src/components/views/contact/Contact.css
  src/components/views/contact/Contact.jsx
  src/components/views/contact/index.jsx
  src/components/views/home/banner/Banner.css
  src/components/views/home/banner/Banner.jsx
  src/components/views/home/services/Services.css
  src/components/views/home/services/Services.jsx
  src/components/views/home/travelDetails/Traval.css
  src/components/views/home/travelDetails/TravelDetails.jsx
  src/index.css
  src/main.jsx
Labels: feature

#20 Adjustment UI update contact page layout fix
  src/App.jsx
  src/components/core/footer/Footer.css
  src/components/core/footer/Footer.jsx
  src/components/views/contact/Contact.css
  src/components/views/contact/Contact.jsx
  src/components/views/privacyPolicy/PrivacyPolicy.css
  src/components/views/privacyPolicy/PrivacyPolicy.jsx
  src/components/views/termsCondition/TermsCondition.css
  src/components/views/termsCondition/TermsCondition.jsx
  src/index.css
  src/main.jsx
Labels: feature
